export const PROJECT_TYPES = [
    { id: 1, name: 'Airports' },
    { id: 2, name: 'Arena' },
    { id: 3, name: 'Bridge' },
    { id: 4, name: 'Data Centers' },
    { id: 5, name: 'Factory' },
    { id: 6, name: 'Federal Government' },
    { id: 7, name: 'Hospital' },
    { id: 8, name: 'Hotel' },
    { id: 9, name: 'Large Scale Retail' },
    { id: 10, name: 'Military' },
    { id: 11, name: 'Multi-Building Educational' },
    { id: 12, name: 'Multi-Building Resort' },
    { id: 13, name: 'Multi-Story Mixed use' },
    { id: 14, name: 'Multi-Story Office' },
    { id: 15, name: 'Multi-Story Residential' },
    { id: 16, name: 'Municipal Government' },
    { id: 17, name: 'Other Transportation' },
    { id: 18, name: 'Power Plants' },
    { id: 19, name: 'Rail' },
    { id: 20, name: 'Restaurant' },
    { id: 21, name: 'Retail' },
    { id: 22, name: 'Road/Highway' },
    { id: 23, name: 'School' },
    { id: 24, name: 'Specialized Facility' },
    { id: 25, name: 'Theater' },
    { id: 26, name: 'Tunnel' },
    { id: 27, name: 'Warehouses' },
    { id: 28, name: 'Water/Waste Management' }
];
